### ISSUE TITLE
iOS build Parent is called on an empty path

### ISSUE THREAD

**Issue by LoopIssuer** [natmlx/videokit#51]
Hi,
When building for iOS with NatML Videokit and Meet Segmentation, I receive below error, please help.
```
Unhandled exception: System.InvalidOperationException: Parent is called on an empty path

   at NiceIO.NPath.get_Parent() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 144

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at NiceIO.NPath.EnsureParentDirectoryExists() in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 767

   at NiceIO.NPath.EnsureDirectoryExists(NPath append) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Common35/NiceIO.cs:line 762

   at il2cpp.Il2CppOptionParser.SetupOtherArguments(Il2CppCommandLineArguments il2CppCommandLineArguments, List`1 foundAssemblies) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Il2CppOptionParser.cs:line 133

   at il2cpp.Il2CppOptionParser.ParseArguments(String[] args, Boolean& continueToRun, ExitCode& exitCode, RuntimePlatform& platform, Il2CppCommandLineArguments& il2cppCommandLineArguments, BuildingOptions& buildingOptions) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Il2CppOptionParser.cs:line 67

   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture, Boolean throwExceptions) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Program.cs:line 61

   at il2cpp.Program.Main(String[] args) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Program.cs:line 36

Command PhaseScriptExecution failed with a nonzero exit code`
```

**Comment by olokobayusuf** [comment]
[This is a Unity bug](https://forum.unity.com/threads/xcode-build-error-after-upgrading-to-2022-2-0.1371966/page-2#post-8762887), not a bug in VideoKit, NatML, or Meet.
